version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9 #creates an image to run my tests
    steps:
      - checkout
      - run: echo "intalling"
      - run: npm install
  test:
    docker:
      - image: circleci/node:8.91 #creates an image to run my tests
    steps:
      - checkout
      - run: echo "testing"
      - run: npm test
  silly:
    docker:
      - image: circleci/node:8.9 #creates an image to run my tests
    steps:
      - checkout
      - run: echo "silly step"
workflows:
  version: 2
  build_test_lint:
    jobs:
      - build
      - silly
      - test:
          requires:
            - silly


